# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_SOC_EXYNOS8895) += exynos8895-dream2lte_eur_open_10.dtb
dtb-$(CONFIG_SOC_EXYNOS8895) += exynos8895-dreamlte_eur_open_10.dtb

dtb-$(CONFIG_ARCH_EXYNOS7) += exynos7-espresso.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
