# SPDX-License-Identifier: GPL-2.0
dtb-y += exynos8895-dreamlte_eur_open_05.dtb
dtb-y += exynos8895-dreamlte_eur_open_07.dtb
dtb-y += exynos8895-dreamlte_eur_open_08.dtb
dtb-y += exynos8895-dreamlte_eur_open_09.dtb
dtb-y += exynos8895-dreamlte_eur_open_10.dtb

#dtb-$(CONFIG_ARCH_EXYNOS7) += exynos7-espresso.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb

